# Tells Symfony to look for routes defined as annotations in /src/Controller
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
